### ISSUE TITLE
界面错乱问题

### ISSUE THREAD

**Issue by Leawind** [LEAWIND/SubjectSystem#1]
当首页已经被打印到控制台的时候，如果更改窗口大小，就有可能导致显示错乱，即使将窗口恢复成原来的大小也没用。
![屏幕截图 2022-05-19 224213](https://user-images.githubusercontent.com/49919003/169323725-43e74f50-e22f-482a-95f0-5e46e42daa6e.jpg)
Windows Terminal
版本: 1.11.3471.0

**Comment by LEAWIND** [comment]
经过测试，windows自带的 “windows控制台主机” 没有这个问题。

**Comment by LEAWIND** [comment]
经过测试，windows自带的 “windows控制台主机” 没有这个问题。

**Comment by Leawind** [comment]
经过测试，windows原生控制台主机没有这个问题。
